// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://odfxvffuzfxbvoyujzrv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9kZnh2ZmZ1emZ4YnZveXVqenJ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY0NTg5MDksImV4cCI6MjA1MjAzNDkwOX0.mvr2jgedsYAVIlDt1emVWOWV5HArRhBnstpYr_0WrDg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);